config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :schedules, only: [:new, :edit, :create, :update, :destroy]
  get '/calendar/:year/:month', to: 'calendar#index', as: 'calendar'

  root 'calendar#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
# frozen_string_literal: true

class Schedule < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :schedules
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
    @today = Date.today
    @year = params[:year].to_i
    @month = params[:month].to_i
    @users = User.all


    if @year == 0 && @month == 0
      @year = @today.year
      @month = @today.month
    end
    if @month == 0
      @year -= 1
      @month = 12
    elsif @month == 13
      @year += 1
      @month = 1
    end
      dates = []

      first_date_of_month = Date.new(@year, @month, 1)

      first_date_of_month.wday.downto(1) do |i|
        dates.push(first_date_of_month - i)
      end

      (0..31).each do |i|
        date = first_date_of_month + i
        break unless date.month == first_date_of_month.month
        dates.push(date)
      end
      @weeks = dates.each_slice(7).to_a

      last_date_of_month = @weeks[-1][-1]

      unless last_date_of_month.saturday?
        until @weeks[-1][-1].saturday?
          last_date_of_month = @weeks[-1][-1]
          next_day = last_date_of_month.next_day
          @weeks[-1].push(next_day)
        end
      end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @today = Date.today
    first_date_of_month = Date.new(@today.year, @today.month, 1)

    dates = []

    first_date_of_month.wday.downto(1) do |i|
      dates.push(first_date_of_month - i)
    end

    (0..31).each do |i|
      date = first_date_of_month + i
      break unless date.month == first_date_of_month.month
      dates.push(date)
    end
    @weeks = dates.each_slice(7).to_a

    last_date_of_month = @weeks[-1][-1]

    unless last_date_of_month.saturday?
      until @weeks[-1][-1].saturday?
        last_date_of_month = @weeks[-1][-1]
        next_day = last_date_of_month.next_day
        @weeks[-1].push(next_day)
      end
    end

    @users = User.all
  end

  def create
    schedule = Schedule.new(schedule_params)
    if schedule.save
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
  end

  def update
    schedule = Schedule.find(params[:id])
    if schedule.update(schedule_params)
      redirect_back(fallback_location: root_path)
    end
  end

  private

    def schedule_params
      params.require(:schedule).permit(:user_id, :first_date_of_week, :scheduled_date, :status)
    end

    def calendar_params
      params.permit(:year, :month)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: session_params[:name])

    if user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to user_path(session[:user_id])
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url
  end

  private

    def session_params
      params.require(:session).permit(:name, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_url
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_url
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def person_in_charge
    true
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  def options(users)
    options_for_select = []
    users.each do |user|
      options_for_select.push([user.name, user.id])
    end
    options_for_select
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendar/index.html.erb
<div class="mt-5 display-4">
  <%= link_to '<', calendar_path(year: @year, month: @month - 1) %>
  <span><%= @year %></span>年
  <span><%= @month %></span>月
  <%= link_to '>', calendar_path(year:@year, month: @month + 1), data: {"turbolinks" => false} %>
</div>

<table class="table mt-5">
  <thead class="thead-dark">
    <tr>
      <th scope="col">担当者</th><th scope="col">日</th><th scope="col">月</th><th scope="col">火</th><th scope="col">水</th><th scope="col">木</th><th scope="col">金</th><th scope="col">土</th><th scope="col">完了?</th>
    </tr>
  </thead>
  <tbody>
    <% @weeks.each_with_index do |week, index| %>
      <% schedule = Schedule.find_by(first_date_of_week: week[0]) || Schedule.new(first_date_of_week: week[0]) %>
      <% form_id = "schedule_form_#{index}" %>
      <tr>
        <td>
          <%= form_for schedule, html: { id: form_id } do |f| %>
          <div class="form-group">
            <%= f.select :user_id, options(@users), {include_blank: ''}, class: 'select-box form-control' %>
          </div>
            <%= f.hidden_field :scheduled_date, class: 'scheduled-date' %>
            <%= f.hidden_field :first_date_of_week %>
          <% end %>
        </td>
        <% week.each do |date| %>
          <% date_classes = ['date'] %>
          <% date_classes.push('scheduled-date') if date == schedule.scheduled_date %>
          <% date_classes.push('finished') if schedule.status && date == schedule.scheduled_date %>
          <% date_classes.push('today') if date == @today %>
          <td class="<%= date_classes.join(' ') %>" data-date="<%= date %>" data-form-id="<%= form_id %>">
            <%= date.day %>
          </td>
        <% end %>
        <td data-form-id="<%= form_id %>">
          <%= form_for schedule, html: {class: 'radio-box'} do |f| %>
            <%= f.radio_button :status, true %>
            <%= f.label :status, '完了', {value: true} %>
            <%= f.radio_button :status, false %>
            <%= f.label :status, '未完了', {value: false} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>unicleaner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Unicleaner', root_path, class: 'navbar-brand' %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'カレンダー', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'ユーザー一覧', users_path, class: 'nav-link' %>
        </li>
      </ul>
    </nav>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/schedules/edit.html.erb
<h1>hello, world</h1>

app/views/schedules/index.html.erb
<span><%= @today.year %></span>年
<span><%= @today.month %></span>月
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">担当者</th><th scope="col">日</th><th scope="col">月</th><th scope="col">火</th><th scope="col">水</th><th scope="col">木</th><th scope="col">金</th><th scope="col">土</th><th scope="col">完了?</th>
    </tr>
  </thead>
  <tbody>
    <% @weeks.each_with_index do |week, index| %>
      <% schedule = Schedule.find_by(first_date_of_week: week[0]) || Schedule.new(first_date_of_week: week[0]) %>
      <% form_id = "schedule_form_#{index}" %>
      <tr>
        <td>
          <%= form_for schedule, html: { id: form_id } do |f| %>
            <%= f.select :user_id, options(@users), {include_blank: ''}, class: 'select-box' %>
            <%= f.hidden_field :scheduled_date, class: 'scheduled-date' %>
            <%= f.hidden_field :first_date_of_week %>
          <% end %>
        </td>
        <% week.each do |date| %>
          <% date_classes = ['date'] %>
          <% date_classes.push('scheduled-date') if date == schedule.scheduled_date %>
          <% date_classes.push('finished') if schedule.status && date == schedule.scheduled_date %>
          <td class="<%= date_classes.join(' ') %>" data-date="<%= date %>" data-form-id="<%= form_id %>">
            <div class="<%= (date == @today) ? 'today' : '' %>">
              <%= date.day %>
            </div>
          </td>
        <% end %>
        <td data-form-id="<%= form_id %>">
          <%= form_for schedule, html: {class: 'radio-box'} do |f| %>
            <%= f.radio_button :status, true %>
            <%= f.label :status, '完了', {value: true} %>
            <%= f.radio_button :status, false %>
            <%= f.label :status, '未完了', {value: false} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/schedules/new.html.erb
<%= form_with url: schedules_path, scope: :schedule, model: @shedule do |f| %>
  <div class="form-group">
    <%= f.label :scheduled_date, '作業日' %>
    <%= f.select :scheduled_date, option(current_user), { include_blank: '選択してください' }, class: 'form-control' %>
  </div>
    <%= f.submit '決定する', class: 'btn btn-primary' %>
<% end %>
<%= current_user.name %>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= f.submit '登録する', class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<%= render partial: 'form', locals: { user: @user } %>

app/views/users/index.html.erb
<div class="card mt-5">
  <ul class="list-group list-group-flush">
    <% @users.each do |user| %>
      <li class="list-group-item">
        <%= user.name %>
        <%= link_to '編集', edit_user_path(user) %>
        <%= link_to '削除', user, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    <% end %>
  </ul>
</div>
<%= link_to '新規登録', new_user_path, class: 'btn btn-primary mt-5' %>

app/views/users/new.html.erb
<%= render partial: 'form', locals: { user: @user } %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>